### ISSUE TITLE
Séparer la page Composer and pieces en 3 sous pages

### ISSUE THREAD

**Issue by melian-e** [Melomania-be/front#1]
### Description
Le but est de rendre ces pages plus lisibles. Il faut les séparer en trois sous pages et rendre l'affichages des éléments plus facile à lire (pour l'instant l'affichage est uniquement avec un select). Ce qui serait intéressant serait d'utiliser le module de filtre.

### Graphismes
Faire en sorte que les pages soient plus jolies

### Nouvelles pages
/library/composers
/library/pieces
/library/type_of_pieces

### Ne pas oublier
Il faut absolument mettre à jour les liens ailleur sur le site (utiliser la fonction de recherche vscode).

**Comment by Califano9577** [comment]
lié au back (ajouter les filtres sur les get all)

https://github.com/Melomania-be/back/issues/12
