### ISSUE TITLE
recommandation first contact

### ISSUE THREAD

**Issue by Califano9577** [Melomania-be/front#7]
envoyer des mails pour contacter les recommandations afin de leur demander leur consentement a etre mis dans le reseau (explication du site et demande si ils veulent participer)

**Comment by melian-e** [comment]
Si fonctionnalité confirmé, cela se symbolisera par un bouton sur la page principale de contact permettant une action rapide.

**Comment by melian-e** [comment]
@Califano9577 Les recommendations seront gérés dans /projects/[id]/management dans une nouvelle page toutes les recommendations en lien avec le projet apparaitront. Dans la page on aura la possibilité de les contacters (à la main ou grâce à un envoie de mail unique registration) ou de leurs créer une fiche de contact (qui restera à valider).
